"""Creacion de tablas iniciales

Revision ID: 974424847a0c
Revises: 
Create Date: 2026-02-24 15:31:50.308075

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '974424847a0c'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Egreso',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('fecha', sa.Date(), nullable=True),
    sa.Column('descripcion', sa.String(), nullable=True),
    sa.Column('monto', sa.Float(), nullable=True),
    sa.Column('categoria', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_Egreso_id'), 'Egreso', ['id'], unique=False)
    op.drop_table('egreso')
    op.drop_table('presupuesto')
    op.drop_table('perfil')
    op.alter_column('usuario', 'id',
               existing_type=sa.UUID(),
               type_=sa.String(length=36),
               existing_nullable=False)
    op.alter_column('usuario', 'username',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('usuario', 'password',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.create_index(op.f('ix_usuario_id'), 'usuario', ['id'], unique=False)
    op.create_unique_constraint(None, 'usuario', ['username'])
    op.create_unique_constraint(None, 'usuario', ['password'])
    op.drop_column('usuario', 'role')
    op.drop_column('usuario', 'email')
    op.drop_column('usuario', 'verified')
    op.drop_column('usuario', 'mes_resgistro')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('usuario', sa.Column('mes_resgistro', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('usuario', sa.Column('verified', sa.BOOLEAN(), autoincrement=False, nullable=True))
    op.add_column('usuario', sa.Column('email', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('usuario', sa.Column('role', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'usuario', type_='unique')
    op.drop_constraint(None, 'usuario', type_='unique')
    op.drop_index(op.f('ix_usuario_id'), table_name='usuario')
    op.alter_column('usuario', 'password',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('usuario', 'username',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('usuario', 'id',
               existing_type=sa.String(length=36),
               type_=sa.UUID(),
               existing_nullable=False)
    op.create_table('perfil',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('nombre', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('usuario_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuario.id'], name=op.f('FK_PERFIL_USUARIO')),
    sa.PrimaryKeyConstraint('id', name=op.f('perfil_pkey'))
    )
    op.create_table('presupuesto',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('categoria', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('usuario_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('monto_limite', sa.NUMERIC(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuario.id'], name=op.f('FK_PRESUPUESTO_USUARIO')),
    sa.PrimaryKeyConstraint('id', name=op.f('categoria_pkey'))
    )
    op.create_table('egreso',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('fecha', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.Column('monto', sa.NUMERIC(), autoincrement=False, nullable=False),
    sa.Column('descripcion', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('categoria', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('egreso_pkey'))
    )
    op.drop_index(op.f('ix_Egreso_id'), table_name='Egreso')
    op.drop_table('Egreso')
    # ### end Alembic commands ###
